/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GraphicInterfaces;

import Leilao.Cliente;
import Leilao.InterfaceServ;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author stephany
 */
public class IntCadProduto extends javax.swing.JFrame {

    /**
     * Creates new form IntCadProduto
     */
    public IntCadProduto() {
        initComponents();
        myname.setText(Cliente.mynameis);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        IniPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TimeAuction = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ProductSubmission = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        myname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto ");

        ProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto");

        jLabel3.setText("Descrição");

        ProductDescription.setColumns(20);
        ProductDescription.setRows(5);
        jScrollPane1.setViewportView(ProductDescription);

        jLabel4.setText("Preço Inicial ");

        IniPrice.setText("0,00");

        jLabel5.setText("Duração");

        jLabel6.setText("minutos");

        ProductSubmission.setText("Submeter Produto");
        ProductSubmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductSubmissionActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Vendedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(IniPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(TimeAuction, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(myname, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ProductSubmission))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(IniPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimeAuction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(myname))
                .addGap(18, 18, 18)
                .addComponent(ProductSubmission)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNameActionPerformed

    private void ProductSubmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductSubmissionActionPerformed
        
        try {
            // Comunicação RMI
            InterfaceServ startRMIChannel = Cliente.startRMIChannel();
            
            if(startRMIChannel != null)
            {
                double beginPrince = new Double(IniPrice.getText().replace(",",".").trim());
                int timeAuction = new Integer(TimeAuction.getText().trim());
                long codProduct = System.currentTimeMillis(); // (unicidade) 
                
                /**
                 * Submeter o pedido de cadastrar novo produto ao servidor
                 * Código do produto == tempo em millisegundo da submissão (unicidade)
                 */

                if(startRMIChannel.cadastrarProduto(codProduct, ProductName.getText(), ProductDescription.getText(), beginPrince, timeAuction, myname.getText()))
                {
                    JOptionPane.showMessageDialog(new JFrame(), "Produto Cadastrado com sucesso.", "Resposta Cadastro Produto", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }else
                {
                    JOptionPane.showMessageDialog(new JFrame(), "Produto não foi cadastrado.", "Resposta Cadastro Produto", JOptionPane.ERROR_MESSAGE);
                    dispose();
                }
                
            }else
            {
                System.out.println("Não foi possível abrir canal de comunicação");
            }
            
        } catch (RemoteException | NotBoundException ex) {
            Logger.getLogger(IntCadProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ProductSubmissionActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IniPrice;
    private javax.swing.JTextArea ProductDescription;
    private javax.swing.JTextField ProductName;
    private javax.swing.JButton ProductSubmission;
    private javax.swing.JTextField TimeAuction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel myname;
    // End of variables declaration//GEN-END:variables
}
